apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jboss
    app.kubernetes.io/managed-by: Helm
  name: jboss
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jboss
  type: NodePort
status:
  loadBalancer: {}
